import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
	const { data: session } = useSession();
	const router = useRouter();

	return (
		<div className={styles.container}>
			<Head>
				<title>Coba NextAuth</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{/* Tambahkan Tombol */}
				{session ? (
					<button onClick={() => signOut()}>Log out</button>
				) : (
					<button
						onClick={() => {
							router.push("/auth/login");
						}}
					>
						Sign in
					</button>
				)}
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<Link href="/belakang" passHref>
					<button>Ke Halaman Belakang</button>
				</Link>
			</main>
		</div>
	);
}
